title: Tango And Chaos
description: About Argentine Tango

#permalink: pretty
#permalink: /:chapter/:slug
permalink: none
collections:
  en_book:
    permalink: /:collection/:name
    output: true


remote_theme: pmarsceill/just-the-docs
color_scheme: nil

baseurl: "/draft.tangoandchaos/"
url: "https://tangodata.github.io"

exclude: [
  "Rakefile", "Gemfile", "Gemfile.lock",
  "*.gemspec", "*.gem",
  "node_modules/",
  "package.json", "package-lock.json",
  "script/", "lib/", "bin/",
  "LICENSE.txt", "README.md",
  "core"
]

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-2709176-10

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"

    # Enable or disable the site search
search_enabled: true

########################
## For Development Only
port: 8080
host: 192.168.3.10
#source: source
#destination: docs


