title: Tango And Chaos
description: About Argentine Tango
keywords: "tango, argentina, dance, culture"
#url: "https://tangodata.github.io"
#baseurl: "/draft.tangoandchaos/"
url: "https://draft.tangoandchaos.org"
baseurl: ""
author:
  source: "Rick McGarrey"
  markdown: "Kace Ong"



#============= THEME ======================
#theme: jekyll-theme-modernist
remote_theme: pmarsceill/just-the-docs
#remote_theme: pawamoy/jekyll-readthedocs
permalink: pretty
color_scheme: nil
aux_links:
  "Frozen Site":
    - "https://github.com/tangodata/raw.tangoandchaos"
  "Development Site":
    - "https://github.com/tangodata/draft.tangoandchaos"
  "Sitemap":
    - "sitemap.xml"
  "Feed":
    - "feed.xml"
#ga_tracking: UA-2709176-10
#google_analytics:
# Enable or disable the site search
#search_enabled: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "source/pages"
    values:
      layout: "default"

#============= EXTENSION  ===================
#plugins: [jekyll-paginate-v2]
plugins:
  - jekyll-sitemap
  #- jekyll-feed
  #- jekyll-mentions
  #- jekyll-redirect-from
  #- jemoji
  #- jekyll-seo-tag
  #- jekyll-avatar
  #- jekyll-assets


#============= STRUCTURE ===================
collections:
  en:
    permalink: /:name
    output: true


#============ DEVELOPMENT ==================
## For Development Only
host: 192.168.3.10
port: 8080
#source: source
#destination: docs
exclude: [
  "Rakefile", "Gemfile", "Gemfile.lock",
  "*.gemspec", "*.gem",
  "node_modules/",
  "package.json", "package-lock.json",
  "script/", "lib/", "bin/",
  "LICENSE.txt", "README.md",
  "core"
]



